[inductor] Promote half-precision CPU constants to float
Currently `aten.where` can fail with the following C++ compiler error:
```
error: operands to '?:' have different types 'c10::Half' and 'float'
```

This happens because `ops.load` is overridden to cast Half inputs to float, but
`ops.constant` will load a Half without promoting to float.

ghstack-source-id: 16974b277ca818ced387db2dc6c6297bb343708e
Pull Request resolved: https://github.com/pytorch/pytorch/pull/91224